// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyProtoJava.proto

#ifndef PROTOBUF_MyProtoJava_2eproto__INCLUDED
#define PROTOBUF_MyProtoJava_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_MyProtoJava_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsSendMyDataTestImpl();
void InitDefaultsSendMyDataTest();
inline void InitDefaults() {
  InitDefaultsSendMyDataTest();
}
}  // namespace protobuf_MyProtoJava_2eproto
namespace MyTestProtobufJava {
class SendMyDataTest;
class SendMyDataTestDefaultTypeInternal;
extern SendMyDataTestDefaultTypeInternal _SendMyDataTest_default_instance_;
}  // namespace MyTestProtobufJava
namespace MyTestProtobufJava {

// ===================================================================

class SendMyDataTest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MyTestProtobufJava.SendMyDataTest) */ {
 public:
  SendMyDataTest();
  virtual ~SendMyDataTest();

  SendMyDataTest(const SendMyDataTest& from);

  inline SendMyDataTest& operator=(const SendMyDataTest& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SendMyDataTest(SendMyDataTest&& from) noexcept
    : SendMyDataTest() {
    *this = ::std::move(from);
  }

  inline SendMyDataTest& operator=(SendMyDataTest&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SendMyDataTest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SendMyDataTest* internal_default_instance() {
    return reinterpret_cast<const SendMyDataTest*>(
               &_SendMyDataTest_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(SendMyDataTest* other);
  friend void swap(SendMyDataTest& a, SendMyDataTest& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SendMyDataTest* New() const PROTOBUF_FINAL { return New(NULL); }

  SendMyDataTest* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SendMyDataTest& from);
  void MergeFrom(const SendMyDataTest& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SendMyDataTest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // bytes keyPrivate = 5;
  void clear_keyprivate();
  static const int kKeyPrivateFieldNumber = 5;
  const ::std::string& keyprivate() const;
  void set_keyprivate(const ::std::string& value);
  #if LANG_CXX11
  void set_keyprivate(::std::string&& value);
  #endif
  void set_keyprivate(const char* value);
  void set_keyprivate(const void* value, size_t size);
  ::std::string* mutable_keyprivate();
  ::std::string* release_keyprivate();
  void set_allocated_keyprivate(::std::string* keyprivate);

  // int32 id = 2;
  void clear_id();
  static const int kIdFieldNumber = 2;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // float salary1 = 3;
  void clear_salary1();
  static const int kSalary1FieldNumber = 3;
  float salary1() const;
  void set_salary1(float value);

  // double salary2 = 4;
  void clear_salary2();
  static const int kSalary2FieldNumber = 4;
  double salary2() const;
  void set_salary2(double value);

  // @@protoc_insertion_point(class_scope:MyTestProtobufJava.SendMyDataTest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr keyprivate_;
  ::google::protobuf::int32 id_;
  float salary1_;
  double salary2_;
  mutable int _cached_size_;
  friend struct ::protobuf_MyProtoJava_2eproto::TableStruct;
  friend void ::protobuf_MyProtoJava_2eproto::InitDefaultsSendMyDataTestImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SendMyDataTest

// string name = 1;
inline void SendMyDataTest::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SendMyDataTest::name() const {
  // @@protoc_insertion_point(field_get:MyTestProtobufJava.SendMyDataTest.name)
  return name_.GetNoArena();
}
inline void SendMyDataTest::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MyTestProtobufJava.SendMyDataTest.name)
}
#if LANG_CXX11
inline void SendMyDataTest::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MyTestProtobufJava.SendMyDataTest.name)
}
#endif
inline void SendMyDataTest::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MyTestProtobufJava.SendMyDataTest.name)
}
inline void SendMyDataTest::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MyTestProtobufJava.SendMyDataTest.name)
}
inline ::std::string* SendMyDataTest::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:MyTestProtobufJava.SendMyDataTest.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SendMyDataTest::release_name() {
  // @@protoc_insertion_point(field_release:MyTestProtobufJava.SendMyDataTest.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMyDataTest::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:MyTestProtobufJava.SendMyDataTest.name)
}

// int32 id = 2;
inline void SendMyDataTest::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 SendMyDataTest::id() const {
  // @@protoc_insertion_point(field_get:MyTestProtobufJava.SendMyDataTest.id)
  return id_;
}
inline void SendMyDataTest::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:MyTestProtobufJava.SendMyDataTest.id)
}

// float salary1 = 3;
inline void SendMyDataTest::clear_salary1() {
  salary1_ = 0;
}
inline float SendMyDataTest::salary1() const {
  // @@protoc_insertion_point(field_get:MyTestProtobufJava.SendMyDataTest.salary1)
  return salary1_;
}
inline void SendMyDataTest::set_salary1(float value) {
  
  salary1_ = value;
  // @@protoc_insertion_point(field_set:MyTestProtobufJava.SendMyDataTest.salary1)
}

// double salary2 = 4;
inline void SendMyDataTest::clear_salary2() {
  salary2_ = 0;
}
inline double SendMyDataTest::salary2() const {
  // @@protoc_insertion_point(field_get:MyTestProtobufJava.SendMyDataTest.salary2)
  return salary2_;
}
inline void SendMyDataTest::set_salary2(double value) {
  
  salary2_ = value;
  // @@protoc_insertion_point(field_set:MyTestProtobufJava.SendMyDataTest.salary2)
}

// bytes keyPrivate = 5;
inline void SendMyDataTest::clear_keyprivate() {
  keyprivate_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SendMyDataTest::keyprivate() const {
  // @@protoc_insertion_point(field_get:MyTestProtobufJava.SendMyDataTest.keyPrivate)
  return keyprivate_.GetNoArena();
}
inline void SendMyDataTest::set_keyprivate(const ::std::string& value) {
  
  keyprivate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MyTestProtobufJava.SendMyDataTest.keyPrivate)
}
#if LANG_CXX11
inline void SendMyDataTest::set_keyprivate(::std::string&& value) {
  
  keyprivate_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MyTestProtobufJava.SendMyDataTest.keyPrivate)
}
#endif
inline void SendMyDataTest::set_keyprivate(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  keyprivate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MyTestProtobufJava.SendMyDataTest.keyPrivate)
}
inline void SendMyDataTest::set_keyprivate(const void* value, size_t size) {
  
  keyprivate_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MyTestProtobufJava.SendMyDataTest.keyPrivate)
}
inline ::std::string* SendMyDataTest::mutable_keyprivate() {
  
  // @@protoc_insertion_point(field_mutable:MyTestProtobufJava.SendMyDataTest.keyPrivate)
  return keyprivate_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SendMyDataTest::release_keyprivate() {
  // @@protoc_insertion_point(field_release:MyTestProtobufJava.SendMyDataTest.keyPrivate)
  
  return keyprivate_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMyDataTest::set_allocated_keyprivate(::std::string* keyprivate) {
  if (keyprivate != NULL) {
    
  } else {
    
  }
  keyprivate_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), keyprivate);
  // @@protoc_insertion_point(field_set_allocated:MyTestProtobufJava.SendMyDataTest.keyPrivate)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace MyTestProtobufJava

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MyProtoJava_2eproto__INCLUDED
