/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyTestJNIPackage_nativeMethods */

#ifndef _Included_MyTestJNIPackage_nativeMethods
#define _Included_MyTestJNIPackage_nativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MyTestJNIPackage_nativeMethods
 * Method:    initSaveJavaEnv
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyTestJNIPackage_nativeMethods_initSaveJavaEnv
  (JNIEnv *, jobject);

/*
 * Class:     MyTestJNIPackage_nativeMethods
 * Method:    nativeOne
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyTestJNIPackage_nativeMethods_nativeOne
  (JNIEnv *, jobject);

/*
 * Class:     MyTestJNIPackage_nativeMethods
 * Method:    nativeTwo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_MyTestJNIPackage_nativeMethods_nativeTwo
  (JNIEnv *, jobject);

/*
 * Class:     MyTestJNIPackage_nativeMethods
 * Method:    sendMessage
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_MyTestJNIPackage_nativeMethods_sendMessage
  (JNIEnv *, jobject, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
